name: Packaging

on: ["push"]

jobs:
  cx_Freeze:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [macOS, windows]

    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: pip install cx_Freeze .[gui]
    - run: cxfreeze misc/ilmsdump-gui.py

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}
        path: dist
