name: Packaging

on: ["push"]

jobs:
  pyinstaller:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [macOS, windows]

    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: pip install pyinstaller .[gui]
    - run: pyinstaller misc/ilmsdump-gui.py --hidden-import=PySide2.QtXml

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}
        path: dist
